SRC= C:/Users/shami/Documents/LTTSminiproject/MiniProject_C/3_Implementation/src/foodOrder.c

PROJ=foodOrder.exe

$(PROJ): $(SRC)
	 gcc $(SRC) -o $(PROJ)

run: $(PROJ)
	  ./${PROJ}

clean:
	 rm -rf $(PROJ) 


