name: C/C++ CI Build status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make all
      run: make -C 3_Implementation
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
