name: code-coverage
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install gcov 
      run: sudo apt -y install gcovr
    - name: make coverage
      run: make -C 3_Implementation/ coverage
    - name: GCov Report
      run:  gcovr -r .
